Repository JiejayLan/unifreefrontend, pull requests merged in 2019-11, with the labels that each got.

#31 Navigation signout
  .eslintrc.json
  package-lock.json
  package.json
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/NavBar.stories.js
  src/components/NavBar/__tests__/NavBar.js
  src/components/NavBar/index.js
Labels: Ready

#33 private and public route
  .eslintrc.json
  package-lock.json
  src/routes/AppRouter.js
  src/routes/PrivateRoute.js
  src/routes/PublicRoute.js
Labels: Ready

#36 Style fix
  docs/asset-manifest.json
  docs/iframe.html
  docs/main.7b7e95e75fc9c694162a.bundle.js
  docs/main.7b7e95e75fc9c694162a.bundle.js.map
  docs/main.css
  docs/main.css.map
  docs/main.fc1347ed9716d3c96b1b.bundle.js
  docs/main.fc1347ed9716d3c96b1b.bundle.js.map
  docs/precache-manifest.4ccedb9cc4a608a331c6f0613b15dc02.js
  docs/precache-manifest.bdd12260ee4bad44165ebaf7abd23671.js
  docs/runtime~main.7b7e95e75fc9c694162a.bundle.js
  docs/runtime~main.7b7e95e75fc9c694162a.bundle.js.map
  docs/runtime~main.fc1347ed9716d3c96b1b.bundle.js.map
  docs/service-worker.js
  docs/vendors~main.7b7e95e75fc9c694162a.bundle.js
  docs/vendors~main.7b7e95e75fc9c694162a.bundle.js.map
  docs/vendors~main.fc1347ed9716d3c96b1b.bundle.js
  docs/vendors~main.fc1347ed9716d3c96b1b.bundle.js.map
  package-lock.json
  package.json
  src/_theme.scss
  src/components/Forms/SignInForm/style.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/style.js
  src/index.js
  src/index.scss
Labels: Ready

#39 Update README.md
  README.md
Labels: hotfix

#40 Merge to master
  .eslintrc.json
  README.md
  docs/asset-manifest.json
  docs/iframe.html
  docs/main.50a1aa1cfa2b48eee245.bundle.js
  docs/main.50a1aa1cfa2b48eee245.bundle.js.map
  docs/main.fc1347ed9716d3c96b1b.bundle.js
  docs/main.fc1347ed9716d3c96b1b.bundle.js.map
  docs/precache-manifest.9d76574f6ed52498f9e8fcf88c277c80.js
  docs/precache-manifest.bdd12260ee4bad44165ebaf7abd23671.js
  docs/runtime~main.50a1aa1cfa2b48eee245.bundle.js
  docs/runtime~main.50a1aa1cfa2b48eee245.bundle.js.map
  docs/runtime~main.fc1347ed9716d3c96b1b.bundle.js.map
  docs/service-worker.js
  docs/vendors~main.50a1aa1cfa2b48eee245.bundle.js
  docs/vendors~main.50a1aa1cfa2b48eee245.bundle.js.map
  docs/vendors~main.fc1347ed9716d3c96b1b.bundle.js
  docs/vendors~main.fc1347ed9716d3c96b1b.bundle.js.map
  package-lock.json
  package.json
  src/_theme.scss
  src/components/Forms/SignInForm/style.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.stories.js
  src/components/NavBar/__tests__/NavBar.js
  src/components/NavBar/index.js
  src/components/NavBar/style.js
  src/index.js
  src/index.scss
  src/routes/AppRouter.js
  src/routes/PrivateRoute.js
  src/routes/PublicRoute.js
Labels: Ready

#44 Route hotfix
  package-lock.json
  src/routes/PrivateRoute.js
  src/routes/PublicRoute.js
Labels: hotfix

#45 Hotfix
  package-lock.json
  src/components/Forms/SignInForm/SignInForm.js
  src/components/NavBar/NavBar.js
  src/routes/PrivateRoute.js
  src/routes/PublicRoute.js
Labels: hotfix

#46 View All post
  docs/asset-manifest.json
  docs/iframe.html
  docs/main.28cb6cf2f38a6a46433d.bundle.js
  docs/main.28cb6cf2f38a6a46433d.bundle.js.map
  docs/main.7757db8b2043f1e540d4.bundle.js
  docs/main.7757db8b2043f1e540d4.bundle.js.map
  docs/precache-manifest.8f1787668e930889e1afc489617074f9.js
  docs/precache-manifest.cfe46cbb52aadd271a1a1fd18859109b.js
  docs/runtime~main.28cb6cf2f38a6a46433d.bundle.js.map
  docs/runtime~main.7757db8b2043f1e540d4.bundle.js
  docs/runtime~main.7757db8b2043f1e540d4.bundle.js.map
  docs/service-worker.js
  docs/vendors~main.28cb6cf2f38a6a46433d.bundle.js
  docs/vendors~main.28cb6cf2f38a6a46433d.bundle.js.map
  docs/vendors~main.7757db8b2043f1e540d4.bundle.js
  docs/vendors~main.7757db8b2043f1e540d4.bundle.js.map
  package-lock.json
  src/components/Posts/AllPost/AllPost.js
  src/components/Posts/AllPost/AllPost.stories.js
  src/components/Posts/AllPost/__tests__/AllPost.js
  src/components/Posts/AllPost/index.js
  src/components/Posts/MainPost/MainPost.js
  src/components/Posts/MainPost/MainPost.stories.js
  src/components/Posts/MainPost/__tests__/MainPost.js
  src/components/Posts/MainPost/index.js
  src/components/Posts/MainPost/style.js
  src/components/Posts/SubPost/SubPost.js
  src/components/Posts/SubPost/SubPost.stories.js
  src/components/Posts/SubPost/__tests__/SubPost.js
  src/components/Posts/SubPost/index.js
  src/components/Posts/SubPost/style.js
  src/components/StateProvider/StateProvider.js
  src/components/StateProvider/index.js
  src/pages/home/Home.js
  src/pages/home/Home.stories.js
  src/pages/home/__tests__/home.js
  src/routes/AppRouter.js
  src/routes/PrivateRoute.js
  src/routes/__tests__/appRouter.js
Labels: Ready

#51 Posts pagination
  package-lock.json
  package.json
  public/images/loader.gif
  src/components/Forms/SignInForm/SignInForm.js
  src/components/Forms/TokenVerifyForm/TokenVerifyForm.js
  src/components/Pagination/Pagination.js
  src/components/Pagination/__tests__/pagination.js
  src/components/Pagination/index.js
  src/components/Pagination/pagination.stories.js
  src/components/Pagination/style.js
  src/components/Posts/AllPost/AllPost.js
  src/components/Posts/AllPost/AllPost.stories.js
  src/components/Posts/AllPost/__tests__/AllPost.js
  src/components/Posts/AllPost/style.js
  src/pages/home/Home.js
  src/services/serviceRequest.js
Labels: Ready

#50 Create Post
  docs/asset-manifest.json
  docs/iframe.html
  docs/index.html
  docs/main.25491f6ae270cc7ba4c2.bundle.js
  docs/main.2817374d4287bdc3789f.bundle.js
  docs/main.7757db8b2043f1e540d4.bundle.js
  docs/main.7757db8b2043f1e540d4.bundle.js.map
  docs/main.e4ceb13354d1b2294579.bundle.js
  docs/main.e4ceb13354d1b2294579.bundle.js.map
  docs/precache-manifest.6e8ec5eb3ecfa256f079ac965f2971c7.js
  docs/precache-manifest.8f1787668e930889e1afc489617074f9.js
  docs/runtime~main.7757db8b2043f1e540d4.bundle.js.map
  docs/runtime~main.e4ceb13354d1b2294579.bundle.js
  docs/runtime~main.e4ceb13354d1b2294579.bundle.js.map
  docs/service-worker.js
  docs/vendors~main.4088278116f8ea4023a0.bundle.js
  docs/vendors~main.6bb5ca2be053521d6692.bundle.js
  docs/vendors~main.7757db8b2043f1e540d4.bundle.js
  docs/vendors~main.7757db8b2043f1e540d4.bundle.js.map
  docs/vendors~main.e4ceb13354d1b2294579.bundle.js
  docs/vendors~main.e4ceb13354d1b2294579.bundle.js.map
  src/components/ErrorMessage/ErrorMessage.js
  src/components/Forms/CreatePostForm/CreatePostForm.js
  src/components/Forms/CreatePostForm/__tests__/CreatePostForm.js
  src/components/Forms/CreatePostForm/createPost.stories.js
  src/components/Forms/CreatePostForm/index.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/__tests__/NavBar.js
  src/components/NavBar/style.js
  src/components/Posts/MainPost/MainPost.js
  src/components/Posts/SubPost/SubPost.js
Labels: Ready

#55 fix NavBar pisition issue
  src/components/ElevationScroll/ElevationScroll.js
  src/components/ElevationScroll/ElevationScroll.stories.js
  src/components/ElevationScroll/__tests__/ElevationScroll.js
  src/components/ElevationScroll/index.js
  src/components/NavBar/NavBar.js
  src/components/ScrollToTop/ScrollToTop.js
  src/components/ScrollToTop/ScrollToTop.stories.js
  src/components/ScrollToTop/__tests__/ScrollToTop.js
  src/components/ScrollToTop/index.js
  src/components/ScrollToTop/style.js
  src/routes/PrivateRoute.js
  src/routes/PublicRoute.js
Labels: Ready

#61 made scrollup faster
  src/components/ScrollToTop/ScrollToTop.js
  src/routes/PrivateRoute.js
  src/routes/PublicRoute.js
Labels: hotfix

#64 Create Comment Component
  src/components/Forms/CommentInput/CommentInput.js
  src/components/Forms/CommentInput/CommentInput.stories.js
  src/components/Forms/CommentInput/__tests__/CommentInput.js
  src/components/Forms/CommentInput/index.js
  src/components/Forms/CommentInput/style.js
  src/components/Posts/IndividualPost/IndividualPost.js
  src/components/ScrollToTop/__tests__/ScrollToTop.js
Labels: Ready, high priority

#67 fix typo error
  src/components/Forms/CommentInput/CommentInput.js
Labels: Ready

#68 fix a warning in commentInput
  src/components/Forms/CommentInput/CommentInput.js
Labels: Ready

#70 fix bug for comment features
  src/components/Comments/ViewComments/ViewComments.js
  src/components/Forms/CommentInput/CommentInput.js
Labels: hotfix

#71 ViewComment to include Pagination
  src/components/Comments/ViewComments/ViewComments.js
Labels: hotfix
